# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Barry Bloye
email: me@barrybloye.co.uk
description: # this means to ignore newlines until "baseurl:"
  Front-end web developer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://barrybloye.co.uk" # the base hostname & protocol for your site
timezone: Europe/London
twitter_username: barrybloye
github_username:  barrybloye

# Build settings
markdown: kramdown
